version: '3'
services:
  db:
    image: couchbase/server:community-5.0.1
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    volumes:
      - $COUCHBASE_DATA_DIR:/opt/couchbase/var
  api:
    image: crowdai-api
    ports:
      - "$PORT:$PORT"
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:8091", "--", "npm", "start"]
    environment:
      NODE_ENV: production       